# Generated by Django 3.2.9 on 2022-09-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_personal_info_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal_info',
            old_name='mobile',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='personal_info',
            name='specialization',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
