# Generated by Django 3.2.9 on 2022-10-03 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_personal_info_signature_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationInformationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.TextField(max_length=300)),
                ('r_department', models.TextField(max_length=300)),
                ('board_university', models.TextField(max_length=300)),
                ('passing_year', models.DateField()),
                ('result', models.IntegerField()),
                ('distinction', models.TextField(max_length=300)),
                ('personal_info', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.personal_info')),
            ],
        ),
    ]
