# Generated by Django 3.2.9 on 2022-10-19 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0028_postinginformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionInformatrion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_designation', models.TextField(max_length=150)),
                ('pro_nature', models.TextField(max_length=150)),
                ('pro_promotion_date', models.DateField()),
                ('pro_order_no', models.TextField(max_length=100)),
                ('pro_order_date', models.DateField()),
                ('pro_remarks', models.TextField(max_length=300)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AchievementInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.TextField(max_length=100)),
                ('achievement_year', models.DateField()),
                ('achievement_description', models.TextField(max_length=400)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
