# Generated by Django 3.2.9 on 2022-11-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20221031_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='r_and_d_projectsinformation',
            name='r_and_d_Project_status',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='r_and_d_projectsinformation',
            name='r_and_d_Project_type',
            field=models.TextField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='researchinterestinformation',
            name='researchInterest_fields',
            field=models.TextField(max_length=200),
        ),
    ]
