# Generated by Django 3.2.9 on 2022-09-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220927_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_info',
            name='pro_pic',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
