# Generated by Django 3.2.9 on 2022-09-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220929_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='pro_pic',
            field=models.ImageField(upload_to='images'),
        ),
    ]
