# Generated by Django 3.2.9 on 2022-09-29 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_personal_info_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_info',
            name='pro_pic',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
