# Generated by Django 3.2.9 on 2022-09-30 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_alter_personal_info_pro_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_info',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Joining_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.TextField(max_length=300)),
                ('grade', models.TextField(max_length=300)),
                ('designation', models.TextField(max_length=300)),
                ('batch', models.TextField(max_length=300)),
                ('workStation', models.TextField(max_length=300)),
                ('joining_date', models.DateField()),
                ('office_name', models.TextField(max_length=300)),
                ('prl_date', models.DateField()),
                ('department', models.TextField(max_length=300)),
                ('order_no_date', models.TextField(max_length=300)),
                ('district', models.TextField(max_length=300)),
                ('conf_date', models.DateField()),
                ('upazila', models.TextField(max_length=300)),
                ('gazatted_date', models.DateField()),
                ('job_nature', models.TextField(max_length=300)),
                ('edndorsement_date', models.TextField()),
                ('personal_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.personal_info')),
            ],
        ),
        migrations.CreateModel(
            name='Contract_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present_address', models.TextField(max_length=300)),
                ('parmanent_address', models.TextField(max_length=300)),
                ('emergency_name', models.TextField(max_length=300)),
                ('present_post_office', models.TextField(max_length=300)),
                ('parmanent_post_office', models.TextField(max_length=300)),
                ('emergency_relation', models.TextField(max_length=300)),
                ('present_police_station', models.TextField(max_length=300)),
                ('parmanent_police_station', models.TextField(max_length=300)),
                ('emergency_address', models.TextField(max_length=300)),
                ('present_district', models.TextField(max_length=300)),
                ('parmanent_district', models.TextField(max_length=300)),
                ('emergency_phone', models.IntegerField()),
                ('present_upazila', models.TextField(max_length=300)),
                ('parmanent_upazila', models.TextField(max_length=300)),
                ('emergency_cell_no', models.IntegerField()),
                ('present_tel_number', models.IntegerField()),
                ('parmanent_tel_number', models.IntegerField()),
                ('emergency_email', models.TextField(max_length=50)),
                ('personal_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.personal_info')),
            ],
        ),
    ]
