# Generated by Django 3.2.9 on 2022-09-30 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20221001_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract_info',
            name='personal_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.personal_info'),
        ),
        migrations.AlterField(
            model_name='joining_info',
            name='personal_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.personal_info'),
        ),
    ]
