# Generated by Django 3.2.9 on 2022-09-30 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0010_auto_20221001_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract_info',
            name='personal_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.personal_info'),
        ),
        migrations.AlterField(
            model_name='joining_info',
            name='personal_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.personal_info'),
        ),
        migrations.AlterField(
            model_name='personal_info',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
