# Generated by Django 3.2.9 on 2022-10-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20221001_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal_info',
            name='signature_pic',
            field=models.ImageField(default=1, upload_to='signatures/'),
            preserve_default=False,
        ),
    ]
