# Generated by Django 3.2.9 on 2022-10-04 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_educationinformationmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EducationInformationModel',
            new_name='EducationInformation',
        ),
    ]
