# Generated by Django 3.2.9 on 2022-10-05 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0016_alter_educationinformation_passing_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationinformation',
            name='personal_info',
        ),
        migrations.AddField(
            model_name='educationinformation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
