# Generated by Django 3.2.9 on 2022-10-05 09:35

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0019_alter_educationinformation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationinformation',
            name='user',
            field=django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_models', to=settings.AUTH_USER_MODEL),
        ),
    ]
