# Generated by Django 3.2.9 on 2022-10-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_educationinformation_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildrenInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clild_name', models.TextField(max_length=150)),
                ('clild_gerder', models.TextField(max_length=50)),
                ('clild_birthDate', models.DateField()),
                ('clild_BirthPlace', models.TextField(max_length=200)),
                ('clild_Remarks', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SpouseInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spouse_name', models.TextField(blank=True, max_length=300)),
                ('spouse_home_district', models.TextField(blank=True, max_length=300)),
                ('spouse_occupation', models.TextField(blank=True, max_length=300)),
                ('spouse_designation', models.TextField(blank=True, max_length=300)),
                ('spouse_org_name', models.TextField(blank=True, max_length=300)),
                ('spouse_org_address', models.TextField(blank=True, max_length=400)),
                ('spouse_cell_no', models.IntegerField(blank=True)),
            ],
        ),
    ]
