# Generated by Django 3.2.9 on 2022-10-18 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0027_traninginformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostingInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_designation', models.TextField(max_length=100)),
                ('p_office', models.TextField(max_length=150)),
                ('p_district', models.TextField(max_length=50)),
                ('p_upazila', models.TextField(max_length=80)),
                ('p_form_date', models.DateField()),
                ('p_to_date', models.DateField()),
                ('p_till_today', models.TextField(max_length=150)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
