# Generated by Django 3.2.9 on 2022-10-28 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0029_achievementinformation_promotioninformatrion'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherActivitiesInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otherActivities_type', models.TextField(max_length=150)),
                ('otherActivities_role', models.TextField(max_length=200)),
                ('otherActivities_form', models.DateField()),
                ('otherActivities_to', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='OtherServiceInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otherService_type', models.TextField(max_length=150)),
                ('otherService_address', models.TextField(max_length=300)),
                ('otherService_designation', models.TextField(max_length=150)),
                ('otherService_form', models.DateField()),
                ('otherService_to', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='personal_info',
            name='about_summary',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='LeaveInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.TextField(max_length=150)),
                ('leave_form', models.DateField()),
                ('leave_to', models.DateField()),
                ('leave_description', models.TextField(max_length=400)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
